[RemoteCommandEntry]

;; comment out AutoEnable and enableRCE definitions below
;; in order to tully disable the RCE feature

AutoEnable = No
enableRCE = start RCE
disableRCE = stop RCE

Interface = usb0
MulticastGroup = 239.1.2.3
Port = 10000

